miniAGV:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  jointFL_position_controller:
    type: position_controllers/JointPositionController
    joint: wheel_supportFL_joint
    pid: {p: 700, i: 50, d: 70}
  
  jointFL_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheelFL_joint
    pid: {p: 700, i: 50, d: 70}

  jointFR_position_controller:
    type: position_controllers/JointPositionController
    joint: wheel_supportFR_joint
    pid: {p: 700, i: 50, d: 70}
  
  jointFR_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheelFR_joint
    pid: {p: 700, i: 50, d: 70}

  jointRL_position_controller:
    type: position_controllers/JointPositionController
    joint: wheel_supportRL_joint
    pid: {p: 700, i: 50, d: 70}
  
  jointRL_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheelRL_joint
    pid: {p: 700, i: 50, d: 70}

  jointRR_position_controller:
    type: position_controllers/JointPositionController
    joint: wheel_supportRR_joint
    pid: {p: 700, i: 50, d: 70}
  
  jointRR_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheelRR_joint
    pid: {p: 700, i: 50, d: 70}

  