joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

four_wheel_steering_controller:
  type: "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['wheelFL_joint', 'wheelFR_joint']
  rear_wheel: ['wheelRL_joint', 'wheelRR_joint']
  front_steering: ['wheel_supportFL_joint', 'wheel_supportFR_joint']
  rear_steering: ['wheel_supportRL_joint', 'wheel_supportRR_joint']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # cmd_vel_timeout: 25.0 # not tested here

  wheel_separation : 0.1492
  wheel_radius : 0.0762
  wheel_steering_y_offset : 0.03

  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  cmd_vel_timeout: 1.0

  base_frame_id: base_link #default: base_link

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.667  # m/s
      min_velocity           : -1.667 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # m/s^2
      min_acceleration       : -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.14  # rad/s
      min_velocity           : -3.14
      has_acceleration_limits: true
      max_acceleration       : 1.0  # rad/s^2
      min_acceleration       : -1.0
  
  /gazebo_ros_control:
      pid_gains:
        wheel_supportFL_joint:
          p: 50
          i: 1
          d: 0.01
        wheel_supportFR_joint:
          p: 50
          i: 1
          d: 0.01
        wheel_supportRL_joint:
          p: 50
          i: 1
          d: 0.01
        wheel_supportRR_joint:
          p: 50
          i: 1
          d: 0.01
        wheelFL_joint: #front_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        wheelFR_joint: #front_right_wheel
          p: 10.0
          i: 1
          d: 0.0
        wheelRL_joint: #rear_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        wheelRR_joint: #rear_right_wheel
          p: 10.0
          i: 1
          d: 0.0